import {title,displayRotation} from '/widget-kit.js?v=0.14.0';
export function mount({element,config,context}){
 let images=[],index=0,error='',failed=false;element.classList.add('image-slideshow');
 element.innerHTML=`${title(config.title || 'Images')}<figure><img><figcaption></figcaption><p class="slideshow-message"></p></figure><nav class="display-pages" data-castboard-ui="local" aria-label="Slideshow pages"></nav>`;
 const image=element.querySelector('img'),caption=element.querySelector('figcaption'),message=element.querySelector('.slideshow-message'),nav=element.querySelector('nav');
 const render=()=>{const focus=nav.querySelector('button:focus')?.dataset.step;index%=Math.max(1,images.length);const item=images[index];image.hidden=!item;caption.hidden=!item || config.showCaptions===false;caption.textContent=item?.caption || '';image.alt=item?.alt || item?.caption || 'Slide';image.style.objectFit=config.fit || 'contain';if(item && (image.getAttribute('src')!==item.url || failed)){failed=false;message.textContent='Loading image…';image.src=item.url;}else if(!item){image.removeAttribute('src');message.textContent=error || 'No images in this playlist';}nav.hidden=config.showControls===false || images.length<2;nav.innerHTML=nav.hidden?'':`<button type="button" data-step="-1">Previous</button><span>${index+1} / ${images.length}</span><button type="button" data-step="1">Next</button>`;if(focus)nav.querySelector(`[data-step="${focus}"]`)?.focus({preventScroll:true});};
 context.listen(image,'load',()=>{message.textContent='';});context.listen(image,'error',()=>{failed=true;message.textContent='Image unavailable. Check its address in Plugins.';});
 context.listen(nav,'click',event=>{const button=event.target.closest('[data-step]');if(!button)return;index=(index+Number(button.dataset.step)+images.length)%images.length;render();});
 displayRotation({element,context,enabled:()=>config.autoRotate!==false,seconds:()=>config.rotationSeconds || 20,ready:()=>images.length>1,advance:()=>{index++;render();}});
 context.schedule(async()=>{try{const data=await context.data(),selected=images[index]?.url;images=data.images;index=Math.max(0,images.findIndex(item=>item.url===selected));error='';element.querySelector('.widget-head small')?.remove();if(data.demo)element.querySelector('.widget-head').insertAdjacentHTML('beforeend','<small>Sample data</small>');}catch{images=[];error='Images unavailable. Check the source in Plugins; retrying automatically.';}render();},(config.refreshSeconds || 60)*1000);
}
