import test from 'node:test';
import assert from 'node:assert/strict';
import http from 'node:http';
import fs from 'node:fs/promises';
import os from 'node:os';
import path from 'node:path';
import { once } from 'node:events';
import { createApp } from '../../../src/server.js';
import { deviceTokenHash } from '../../../src/core/devices.js';

const enabled=process.env.CASTBOARD_BROWSER_TESTS==='1';
test('image and native receivers open the same modal; images accept valid touches once', {skip:!enabled,timeout:60000}, async t=>{
  const {chromium}=await import('playwright');
  const {createFrameRenderer}=await import('../renderer.js');
  const browser=await chromium.launch({headless:true,...(process.env.CASTBOARD_CHROMIUM_PATH?{executablePath:process.env.CASTBOARD_CHROMIUM_PATH}:{})});
  t.after(()=>browser.close());
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'castboard-browser-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const key='only-for-automated-test-device-connections';
  const baseDevice={name:'Test',screenId:'home',mode:'frame',width:480,height:320,format:'rgb565',refreshMs:5000,enabled:true,touch:true,allowActions:false,tokenHash:deviceTokenHash(key)};
  const config={server:{host:'127.0.0.1',port:8787},branding:{timeZone:'UTC'},plugins:{clock:{enabled:true}},screens:{home:{title:'Home',path:'/',type:'single',panels:[{id:'clock',plugin:'clock',interaction:{type:'modal',screenId:'details'}}]},details:{title:'Clock details',path:'/details',type:'single',presentation:'modal',viewport:{width:400,height:230},appearance:{background:'#203d60',fontFamily:'mono'},panels:[{id:'detail-clock',plugin:'clock'}]}},devices:{image:baseDevice,native:{...baseDevice,name:'Native',mode:'native'}}};
  const configPath=path.join(dir,'config.json');await fs.writeFile(configPath,JSON.stringify(config));
  const app=await createApp({loadedConfig:{config,rawConfig:structuredClone(config),configPath,configDir:dir}});
  app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(()=>{app.server.close();app.server.closeAllConnections();});
  const origin=`http://127.0.0.1:${app.server.address().port}`;
  const renderer=createFrameRenderer({browser,appOrigin:origin});t.after(()=>renderer.dispose());
  const input={id:'image',token:key,width:480,height:320,format:'rgb565',revision:'test'};
  const before=await renderer.render(input);assert.equal(before.buffer.length,480*320*2);
  const touched=await renderer.render({...input,event:{frameId:before.frameId,eventId:'touch0001',x:80,y:80}});
  assert.notEqual(touched.frameId,before.frameId);
  const duplicate=await renderer.render({...input,event:{frameId:before.frameId,eventId:'touch0001',x:80,y:80}});
  assert.equal(duplicate.frameId,touched.frameId);
  await assert.rejects(renderer.render({...input,event:{frameId:before.frameId,eventId:'touch0002',x:80,y:80}}),/fresh frame/);
  await assert.rejects(renderer.render({...input,event:{frameId:touched.frameId,eventId:'badcoords',x:500,y:80}}),/outside/);
  const scene=await(await fetch(origin+'/api/devices/native/scene',{headers:{Authorization:`Bearer ${key}`}})).json();
  const opened=await(await fetch(origin+'/api/devices/native/events',{method:'POST',headers:{Authorization:`Bearer ${key}`,'Content-Type':'application/json'},body:JSON.stringify({sceneId:scene.sceneId,eventId:'native001',event:'panel:clock'})})).json();
  assert.equal(opened.title,'Clock details');assert.equal(opened.modal,true);
  // Separate browser sessions must not leak navigation between devices.
  const second=await renderer.render({...input,id:'native'});assert.equal(second.buffer.length,before.buffer.length);
  assert.notEqual(second.frameId,touched.frameId);
  const jpeg=await renderer.render({...input,format:'jpeg'});assert.equal(jpeg.buffer[0],0xff);assert.equal(jpeg.buffer[1],0xd8);
});

test('Studio previews navigate modals but never send plugin actions; device forms save and reconnect', {skip:!enabled,timeout:60000},async t=>{
  const {chromium}=await import('playwright');
  const browser=await chromium.launch({headless:true,...(process.env.CASTBOARD_CHROMIUM_PATH?{executablePath:process.env.CASTBOARD_CHROMIUM_PATH}:{})});t.after(()=>browser.close());
  const dir=await fs.mkdtemp(path.join(os.tmpdir(),'castboard-studio-'));t.after(()=>fs.rm(dir,{recursive:true,force:true}));
  const config={server:{host:'127.0.0.1',port:8787},branding:{timeZone:'UTC'},plugins:{clock:{enabled:true},spotify:{enabled:true,provider:'demo',controllable:true}},screens:{home:{path:'/',type:'single',panels:[{id:'clock',plugin:'clock',interaction:{type:'modal',screenId:'details'}}]},details:{title:'Music details',path:'/details',type:'single',presentation:'modal',panels:[{id:'music',plugin:'spotify',interaction:{type:'action',action:'toggle'}}]}}};
  const configPath=path.join(dir,'config.json');await fs.writeFile(configPath,JSON.stringify(config));
  const app=await createApp({loadedConfig:{config,rawConfig:structuredClone(config),configPath,configDir:dir}});app.server.listen(0,'127.0.0.1');await once(app.server,'listening');t.after(()=>{app.server.close();app.server.closeAllConnections();});
  const origin=`http://127.0.0.1:${app.server.address().port}`;
  const page=await browser.newPage({viewport:{width:1440,height:960}});const errors=[],actions=[];
  page.on('pageerror',error=>errors.push(error.message));page.on('request',request=>{if(request.url().endsWith('/action'))actions.push(request.url());});
  await page.goto(origin+'/admin');await page.waitForSelector('#screen-list button');
  await page.locator('[data-mode="preview"]').click();
  const frame=page.frameLocator('#live-preview');
  await frame.locator('.panel-interaction').click();await frame.locator('dialog[open] h2').waitFor();
  assert.equal(await frame.locator('dialog[open] h2').textContent(),'Music details');
  await frame.locator('dialog .panel-interaction').click();
  assert.equal(actions.length,0);
  await page.locator('#reset-preview').click();await frame.locator('dialog[open]').waitFor({state:'detached'});await frame.locator('#dashboard .panel-interaction').waitFor();
  assert.equal(await frame.locator('dialog[open]').count(),0);
  await page.goto(origin+'/admin/devices');await page.locator('#first-device').click();
  await page.locator('#device-name').fill('Small screen');await page.locator('#device-mode').selectOption('native');
  await page.locator('#device-form button[type=submit]').click();await page.locator('#key-dialog[open]').waitFor();
  const connection=JSON.parse(await page.locator('#device-connection').inputValue());assert.equal(connection.deviceId,'small-screen');assert.equal(connection.connectionKey.length,43);
  await page.locator('#key-dialog .primary').click();await page.waitForFunction(()=>document.querySelector('#device-connection').value==='');
  assert.equal(await page.locator('#device-connection').inputValue(),'');
  assert.equal((await fetch(origin+'/api/devices/small-screen/config',{headers:{Authorization:`Bearer ${connection.connectionKey}`}})).status,200);
  assert.deepEqual(errors,[]);
});
