import fs from 'node:fs/promises';
import path from 'node:path';
import {fileURLToPath} from 'node:url';
const root=fileURLToPath(new URL('..',import.meta.url)),check=process.argv.includes('--check');
const escape=value=>String(value??'').replace(/\|/g,'\\|').replace(/\n/g,' ');
const docs=[];let changed=0;
for(const id of (await fs.readdir(path.join(root,'plugins'))).sort()){
 const dir=path.join(root,'plugins',id);let manifest;try{manifest=JSON.parse(await fs.readFile(path.join(dir,'plugin.json'),'utf8'));}catch{continue;}
 const hasWidget=await fs.access(path.join(dir,'widget.js')).then(()=>true,()=>false);
 const properties=manifest.settingsSchema?.properties||{},providers=properties.provider?.enum||[];
 const table=(fields,defaults={})=>Object.entries(fields).map(([key,field])=>{
  const constraints=[field.enum?field.enum.map(value=>field.enumLabels?.[value]||value).join(', '):field.type,field.minimum!==undefined?`min ${field.minimum}`:'',field.maximum!==undefined?`max ${field.maximum}`:'',field.maxItems!==undefined?`up to ${field.maxItems} items`:'',field.maxLength!==undefined?`up to ${field.maxLength} characters`:''].filter(Boolean).join('; ');
  const value=defaults[key]??field.default;
  return `| ${escape(field.title||key)} | \`${key}\` | ${escape(constraints)} | ${escape(value===undefined?'—':typeof value==='object'?JSON.stringify(value):value)} | ${escape(field.description||'')} |`;
 }).join('\n');
 const sourceGuide=providers.length?`Available sources: ${providers.map(p=>`**${properties.provider.enumLabels?.[p]||p}** (\`${p}\`)`).join(', ')}.\n\n${providers.includes('demo')?'Start with **Sample data** to try the layout without an external service. ':''}${providers.includes('inline')?'Choose **Enter here** to enter your own content. ':''}${providers.some(p=>['http-json','file-json'].includes(p))?'HTTP and file JSON must match the [canonical contracts](../../docs/PLUGIN-CONTRACTS.md). File paths are relative to the Castboard configuration. JSON files and HTTP responses are limited to 1 MiB. ':''}See the [configuration guide](../../docs/CONFIGURATION.md) for environment references and secret values.` : manifest.defaultBindings?`This package uses source connections listed below. Admin installs the required packages and connects them automatically. The [dashboard panel guide](../../docs/AMBIENT-PLUGINS.md) explains bridge routes and canonical source adapters.` : `This package operates locally without an external data service. See [plugin authoring](../../docs/PLUGINS.md) for its lifecycle and extension interfaces.`;
 const connections=Object.entries(manifest.defaultBindings||{}).map(([alias,type])=>`| \`${alias}\` | [${type}](../${type}/README.md) |`).join('\n');
 const support=hasWidget?`Add the installed copy to a screen with **Add to a screen**. Screen Studio can override the display settings below for each panel. Browser rendering supports phones, tablets, kiosks and Cast displays; image mode renders the same view for an embedded receiver. Native mode is supported only by packages with a native view; use image mode for camera/video and rich companion panels.\n\nA provider failure is isolated to its panel. It retries on the configured refresh cadence. Core data widgets show an unavailable state; RSS news can retain its previous update and label it as stale. Demo values are illustrative. Camera demo mode does not contact a live camera.` : `This is a ${manifest.category==='Support'?'support':'source'} package. Connect it through a display plugin’s **Source connections**; it does not appear as a panel by itself. Use **Test connection** when the package exposes data. An upstream failure is reported to the consuming panel, which retries on its own cadence.`;
 const options=manifest.optionSchema?.properties||{};
 const text=`# ${manifest.name}\n\n${manifest.description}\n\nPackage ID: \`${id}\`. Category: ${manifest.category}. MIT licensed. Names shown in admin can be changed for each installed copy; package IDs stay stable.\n\n## Set up\n\nInstall from **Plugins → Library**. Select the installed copy, give it a name, choose its content source and save its settings. Multiple copies can use separate sources and defaults.\n\n${sourceGuide}\n\n${support}${manifest.displayNotes?`\n\n${manifest.displayNotes}`:''}\n\n## Connection settings\n\n${Object.keys(properties).length?`| Setting | Key | Accepted values | Default | Notes |\n| --- | --- | --- | --- | --- |\n${table(properties,manifest.defaultConfig)}`:'This support package has no connection settings.'}\n\n${connections?`## Source connections\n\n| Connection | Default package |\n| --- | --- |\n${connections}\n\nCompatible copies can replace these connections in admin.\n\n`:''}${Object.keys(options).length?`## Panel overrides\n\nPanel overrides affect only that panel. Source credentials and content settings remain on the installed plugin.\n\n| Setting | Key | Accepted values | Default | Notes |\n| --- | --- | --- | --- | --- |\n${table(options)}\n\n`:''}## Privacy and maintenance\n\nPrivate headers and tokens stay on the server; source connections are separate from display options. Use environment references for credentials; keep local configuration and personal data out of Git. Installing an external plugin loads trusted server code.\n\nSee [the catalog](../../docs/PLUGIN-CATALOG.md), [source contracts](../../docs/PLUGIN-CONTRACTS.md), [panel bridge contracts](../../docs/AMBIENT-PLUGINS.md) and [authoring guide](../../docs/PLUGINS.md). Report reproducible issues with the package ID, provider type and redacted data shape.\n\n<!-- Generated by scripts/plugin-docs.mjs; update plugin.json and regenerate. -->\n`;
 const destination=path.join(dir,'README.md'),old=await fs.readFile(destination,'utf8').catch(()=> '');if(old!==text){changed++;if(!check)await fs.writeFile(destination,text);}
 docs.push({id,...manifest,hasWidget});
}
const catalog=`# Plugin catalog\n\nInstall from **Plugins → Library**. Give each copy a name and connect its sources. Use screen panel overrides to reuse a source in different layouts. All packages are MIT licensed. Package IDs are retained for existing configurations.\n\nThe library separates complete display plugins, companion dashboard panels, data connectors and support packages. Use complete display plugins for canonical JSON, ICS, RSS and direct integrations. Companion panels offer coordinated styling through the shared theme and runtime; their source adapters can connect canonical plugins or a compatible service bridge.\n\n| Name | Purpose | Category | Guide |\n| --- | --- | --- | --- |\n${docs.map(p=>`| ${escape(p.name)} | ${escape(p.description)} | ${p.category} | [\`${p.id}\`](../plugins/${p.id}/README.md) |`).join('\n')}\n\nFor reusable home, lobby and event layouts, see [the sample screens](../examples/community/README.md). For input formats, see [source contracts](PLUGIN-CONTRACTS.md). For failure recovery and privacy, see each package guide.\n\n<!-- Generated by scripts/plugin-docs.mjs. -->\n`;
const catalogPath=path.join(root,'docs/PLUGIN-CATALOG.md');if(await fs.readFile(catalogPath,'utf8').catch(()=> '')!==catalog){changed++;if(!check)await fs.writeFile(catalogPath,catalog);}
if(check&&changed){console.error(`${changed} plugin guides need regenerating: npm run docs:plugins`);process.exitCode=1;}else console.log(`${check?'Verified':'Generated'} ${docs.length} plugin guides and catalog.`);
